# Combine Richard's biomasses, yields and catch size distributions
# with Jess's survey size distributions
library(dplyr)
library(ggplot2)
library(mizer)
library(mizerEcopath)

# Data Richard ----

load("inst/species_info_GD_length.Rdata")
# n:            no. of rows in survey data in which the category occurs
# Snfish:       no. of fish in the category (sometimes there is >1 fish in
#                                            a row)
# SnfishQ:      no. of fish in the sea after allowing for catchabilities
#               of survey gears
# SndensQ.km2:  corresponding density of the category allowing for area
#               swept by survey trawls (/km2)
# Swdens.t.km2: biomass density of the category allowing for weight of
#               fish (t /km2)
# Fmean.yr:     a weighted mean fishing mortality rate (/yr)
# SY.t.km2.yr:  yield generated by the category (t /km2 /yr)
df <- species_info_GD_length |>
    rename(species = common.name,
           length = FishLength_cm) |>
    mutate(species = ifelse(species == "Dover sole", "Sole", species))

biomass_df <- df |>
    group_by(species) |>
    summarise(biomass_observed = sum(Swdens.t.km2))
yield_df <- df |>
    group_by(species) |>
    summarise(yield_observed = sum(SY.t.km2.yr))
survey_df <- df |>
    group_by(species, length) |>
    summarise(catch = sum(Snfish)) |>
    mutate(dl = 1, gear = "survey")
catch_Richard <- df |>
    group_by(species, length) |>
    summarise(catch = sum(Fmean.yr * SndensQ.km2)) |>
    mutate(dl = 1, gear = "commercial")

# Size distributions Jess ----

survey_Jess <- survey_length_distribution
catch_Jess <- catch_distribution |>
    group_by(species, length, dl) |>
    summarise(catch = sum(catch)) |>
    mutate(gear = "commercial")

# compare_catch_densities(catch_Jess, survey_Jess, "Catch", "Survey")
# compare_catch_densities(catch_Jess, catch_Richard, "Jess", "Richard")
# compare_catch_densities(survey_Jess, catch_Richard, "Jess", "Richard")

# Use survey from Jess (because it includes smaller than 20cm)
# Use catch from Richard (because the yield was calculated from this)
catch <- rbind(catch_Richard, survey_Jess)
l_max <- catch |>
    group_by(species) |>
    summarise(l_max = max(length + dl) * 1.1)

# Scale up commercial catches to have same number of fish as
# the survey
scale_factors <- catch |>
    group_by(species, gear) |>
    summarise(total = sum(catch), .groups = "drop") |>
    tidyr::pivot_wider(names_from = gear, values_from = total) |>
    mutate(factor = survey / commercial) |>
    select(species, factor)
catch <- catch |>
    left_join(scale_factors, by = "species") |>
    mutate(catch = if_else(gear == "commercial", catch * factor, catch)) |>
    select(-factor)

# Species params ----

Jess_sp <- celtic_params@species_params |>
    select(species,
           pred_kernel_type, beta, sigma,
           kernel_exp, kernel_l_l, kernel_u_l, kernel_l_r, kernel_u_r)
James_sp <- readRDS("inst/James_sp.rds")
sp <- James_sp |>
    select(species, a, b, w_mat, age_mat, w_inf, k_vb, t0) |>
    inner_join(Jess_sp, by = "species")

rownames(sp) <- sp$species
sp["Cod", "kernel_l_l"] <- 3.8

sp <- sp |>
    inner_join(biomass_df) |>
    inner_join(l_max)
sp$biomass_cutoff <- l2w(20, sp)

sp$D_ext <- 1

# Gear params ----

# Each species gets two gears: a survey gear and a commercial gear.
gear_defs <- data.frame(gear = c("survey", "commercial"),
                        sel_func = "sigmoid_length",
                        l50 = c(20, 40),
                        l25 = c(18, 38),
                        catchability = c(1e-12, 0.2),
                        yield_weight = c(0, 1))
gp <- cross_join(data.frame(species = sp$species), gear_defs) |>
    left_join(yield_df) |>
    # The observed yield is from the commercial gear only; the survey gear
    # takes a negligible yield.
    mutate(yield_observed = if_else(gear == "survey", 1e-10, yield_observed))

# Save data
save(sp, gp, catch, file = "inst/data_Richard_and_Jess.rda")
