# Use Richard's biomasses, yields and survey size distribution
# from Richard's survey data and Nicola Walker's survey selectivities
# and Richard's fishing mortalities
library(dplyr)
library(ggplot2)
library(mizer)
library(mizerEcopath)

# Data Richard ----

load("inst/species_info_GD_length.Rdata")
# n:            no. of rows in survey data in which the category occurs
# Snfish:       no. of fish in the category (sometimes there is >1 fish in
#                                            a row)
# SnfishQ:      no. of fish in the sea after allowing for catchabilities
#               of survey gears
# SndensQ.km2:  corresponding density of the category allowing for area
#               swept by survey trawls (/km2)
# Swdens.t.km2: biomass density of the category allowing for weight of
#               fish (t /km2)
# Fmean.yr:     a weighted mean fishing mortality rate (/yr)
# SY.t.km2.yr:  yield generated by the category (t /km2 /yr)
df <- species_info_GD_length |>
    rename(species = common.name,
           length = FishLength_cm) |>
    mutate(species = ifelse(species == "Dover sole", "Sole", species))

biomass_df <- df |>
    group_by(species) |>
    summarise(biomass_observed = sum(Swdens.t.km2))

survey_Richard <- df |>
    group_by(species, length) |>
    summarise(catch = sum(Snfish)) |>
    mutate(dl = 1, gear = "survey")

l_max <- survey_Richard |>
    group_by(species) |>
    summarise(l_max = max(length + dl) * 1.1)

# Species params ----
ICES_FMSY <- readr::read_csv("inst/ICES_FMSY.csv") |>
    group_by(SpeciesName) |>
    summarise(FMSY = mean(FMSY, na.rm = TRUE)) |>
    rename(Scientific_name = SpeciesName)
Jess_sp <- celtic_params@species_params |>
    left_join(ICES_FMSY) |>
    select(species, Scientific_name, a, b, w_mat, age_mat,
           pred_kernel_type, beta, sigma,
           kernel_exp, kernel_l_l, kernel_u_l,
           kernel_l_r, kernel_u_r, FMSY)
James_sp <- readRDS("inst/James_sp.rds")
sp <- James_sp |>
    select(species, w_inf, k_vb, t0) |>
    right_join(Jess_sp, by = "species")

rownames(sp) <- sp$species
sp$l_inf <- NA
sp["Hake", c("k_vb", "l_inf", "t0")] <- c(0.178, 110, 0)
sp["Hake", "w_inf"] <- NA
sp["Red gurnard", c("k_vb", "l_inf", "l_mat", "age_mat", "t0")]  <-
    c(0.21, 42.4, 27.59, 3.7, -1.21)
sp["Red gurnard", c("w_inf", "w_mat")] <- NA

sp <- sp |>
    inner_join(biomass_df) |>
    inner_join(l_max)
sp$biomass_cutoff <- l2w(20, sp)

sp$D_ext <- 1

# Gear params ----

# Each species gets two gears: a survey gear and a commercial gear.
gear_defs <- data.frame(gear = c("survey", "commercial"),
                        sel_func = "knife_edge_length",
                        knife_edge_length = 20)
gp <- cross_join(data.frame(species = sp$species), gear_defs)

# Save data
save(sp, gp, survey_Richard, file = "inst/data_Richard_survey.rda")
