# Script to fit von Bertalanffy growth parameters and match catch data
library(dplyr)
library(mizer)
library(mizerEcopath)

Jess_sp <- celtic_params@species_params |>
    select(species,
           #biomass_cutoff, #biomass_observed,
           pred_kernel_type, beta, sigma,
           kernel_exp, kernel_l_l, kernel_u_l, kernel_l_r, kernel_u_r)
James_sp <- readRDS("inst/James_sp.rds")
sp <- James_sp |>
    select(species, a, b, w_mat, age_mat, w_inf, k_vb, t0) |>
    inner_join(Jess_sp, by = "species")

load("inst/species_info_GD_length.Rdata")
# n:            no. of rows in survey data in which the category occurs
# Snfish:       no. of fish in the category (sometimes there is >1 fish in
#                                            a row)
# SnfishQ:      no. of fish in the sea after allowing for catchabilities
#               of survey gears
# SndensQ.km2:  corresponding density of the category allowing for area
#               swept by survey trawls (/km2)
# Swdens.t.km2: biomass density of the category allowing for weight of
#               fish (t /km2)
# Fmean.yr:     a weighted mean fishing mortality rate (/yr)
# SY.t.km2.yr:  yield generated by the category (t /km2 /yr)
df <- species_info_GD_length |>
    rename(species = common.name,
           length = FishLength_cm) |>
    mutate(species = ifelse(species == "Dover sole", "Sole", species)) |>
    filter(species %in% sp$species)

biomass_df <- df |>
    group_by(species) |>
    summarise(biomass_observed = sum(Swdens.t.km2),
              l_max = max(length) * 1.1)
yield_df <- df |>
    group_by(species) |>
    summarise(yield_observed = sum(SY.t.km2.yr))
catch_df <- df |>
    group_by(species, length) |>
    summarise(catch = sum(Fmean.yr * SndensQ.km2)) |>
    mutate(dl = 1, gear = "Total")

sp <- right_join(sp, biomass_df)
sp$biomass_cutoff <- l2w(20, sp)

sp$D_ext <- 1

saveRDS(sp, "inst/sp.rds")

# Load pre-packaged species parameters for Celtic Sea model
sp <- readRDS("inst/sp.rds")

# Initialize von Bertalanffy params using mizerEcopath helper
#p <- newVonBertalanffyParams(sp)
p <- newAllometricParams(sp)

plotDeath(p, species = "Hake", proportion = FALSE)
p@species_params$z_ext
p@given_species_params$z_ext
p@species_params$d
p@given_species_params$d
given_species_params(p)$d <- -.25
p <- setExtMort(p)

# Attach gear parameters matching the selected species
gp <- data.frame(species = sp$species,
                 gear = "Total",
                 sel_func = "sigmoid_length",
                 l50 = 40,
                 l25 = 38,
                 catchability = 0.2) |>
    right_join(yield_df)

gear_params(p) <- gp
initial_effort(p) <- 1

# Bring single-species models to steady state and set Beverton-Holt stock-recruitment
p <- steadySingleSpecies(p) |>
    setBevertonHolt()
p <- matchBiomasses(p)

# Fit selectivity/catchability to match observed Celtic Sea catches
p <- matchCatch(p, catch = catch_df, production_lambda = 0,
                yield_lambda = 1)

#p <- tuneEcopath(p, catch = catch_df, diet = reduced_dm)

# Plot resulting yield comparison
plotYieldVsSpecies(p)
plotBiomassVsSpecies(p)
plotlySpectra(p, power = 2, resource = FALSE)
plotlyFMort(p)
p@species_params$z_ext
p@species_params$D_ext

pd <- matchDiet(p, reduced_dm)
plotDeath(pd, species = "Cod")
plotDeath(pd, species = "Whiting")
plotDeath(pd, species = "Hake", proportion = FALSE)

plotSpectra(pd, power = 2)
pd@species_params$D_ext
plot(getMort(pd), log_y = TRUE)
pd@gear_params$catchability
plotGrowthCurves(p, species_panel = TRUE)
